# Generated by Django 5.0.3 on 2024-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_rename_p_date_product_make_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='make_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
